"""L4 real upstream customization proof (Phase C of the D3 proof).

Runs the ACTUAL upstream `resolve_customization.py` script against a
disposable directory tree that mimics an installed BMAD 6.8.0 + TEA
v1.19.0 project, with an RDX-TEA overlay written per ADR-002.

The resolver script is loaded from the upstream clone at
`rdx-workspace/upstream/BMAD-METHOD` (locked SHA in
`D3_SOURCE_LOCK_ADDENDUM.md §1.1`).

Every assertion below is grounded in an actual JSON output from the
resolver, not a mock.
"""

from __future__ import annotations

import os
import sys
import json
import shutil
import subprocess
from pathlib import Path

import pytest

RDX_TEA_DIR = Path(__file__).resolve().parent.parent.parent
REPO_ROOT = RDX_TEA_DIR.parent
UPSTREAM_ROOT = Path(os.environ.get("RDX_TEA_UPSTREAM_ROOT", str(REPO_ROOT.parent / "upstream")))
WORKSPACE = UPSTREAM_ROOT.parent
UPSTREAM_TEA = UPSTREAM_ROOT / "bmad-method-test-architecture-enterprise"
UPSTREAM_BMAD = UPSTREAM_ROOT / "BMAD-METHOD"
VENV_PY = Path(sys.executable)

# The upstream resolve_customization.py at BMAD v6.8.0 tag.
RESOLVER = UPSTREAM_BMAD / "src" / "scripts" / "resolve_customization.py"
UPSTREAM_TESTARCH_TESTDESIGN = (
    UPSTREAM_TEA / "src" / "workflows" / "testarch" / "bmad-testarch-test-design"
)


@pytest.fixture(scope="module")
def upstream_present() -> None:
    if not RESOLVER.exists():
        pytest.skip(f"upstream resolver missing at {RESOLVER}")
    if not UPSTREAM_TESTARCH_TESTDESIGN.exists():
        pytest.skip(f"upstream TEA skill missing at {UPSTREAM_TESTARCH_TESTDESIGN}")


@pytest.fixture
def disposable_project(tmp_path: Path, upstream_present) -> Path:
    """A `{project-root}` with `_bmad/custom/` and a skill under
    `.claude/skills/bmad-testarch-test-design/` copied from upstream."""
    proj = tmp_path / "proj"
    proj.mkdir()
    (proj / "_bmad").mkdir()
    (proj / "_bmad" / "custom").mkdir()
    # Copy skill root from upstream.
    skill_dst = proj / ".claude" / "skills" / "bmad-testarch-test-design"
    shutil.copytree(UPSTREAM_TESTARCH_TESTDESIGN, skill_dst)
    return proj


def _write_rdx_tea_overlay(proj: Path, extra_user_overlay: bool = False) -> None:
    """Write the ADR-002-compliant `_bmad/custom/bmad-testarch-test-design.toml`
    overlay."""
    overlay = proj / "_bmad" / "custom" / "bmad-testarch-test-design.toml"
    overlay.write_text('''# RDX-TEA overlay for bmad-testarch-test-design.
# Generated by rdx-tea-setup (ADR-002 §5.6 wrapper).
# DO NOT EDIT — regenerate via `python3 -m rdx_tea.setup install`.

[workflow]

# Prepend runs BEFORE persistent_facts (verified against upstream
# bmad-testarch-test-design/SKILL.md §"On Activation" Step 2 → Step 3).
activation_steps_prepend = [
  "Run: python3 {project-root}/_bmad/rdx-tea/scripts/prepare.py --workflow test-design --project-root {project-root}. HALT on non-zero exit.",
]

# persistent_facts references the stable active-context bundle written
# by the prepend step. The path is deterministic per (workflow, project).
persistent_facts = [
  "file:{project-root}/_bmad/rdx-tea/runtime/test-design/active-context.md",
]

# Sidecar binder runs AS THE FINAL TERMINAL INSTRUCTION per upstream
# bmad-testarch-test-design/steps-c/step-05-generate-output.md:232-236.
on_complete = "Run: python3 {project-root}/_bmad/rdx-tea/scripts/binder.py --workflow test-design --project-root {project-root}"
''')
    if extra_user_overlay:
        user = proj / "_bmad" / "custom" / "bmad-testarch-test-design.user.toml"
        user.write_text('''[workflow]

persistent_facts = [
  "The developer prefers Playwright over Cypress for E2E.",
]
''')


def _run_resolver(proj: Path, skill_dir: Path, key: str = "workflow") -> dict:
    """Invoke upstream `resolve_customization.py` and return the merged
    `workflow` block (unwrapped from the resolver's outer envelope)."""
    result = subprocess.run(
        [str(VENV_PY), str(RESOLVER),
         "--skill", str(skill_dir),
         "--key", key],
        cwd=str(proj),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        pytest.fail(
            f"resolver exited {result.returncode}\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
    raw = json.loads(result.stdout)
    # The resolver wraps the merged block in {"workflow": {...}} when
    # `--key workflow` is used. Unwrap for convenience.
    if isinstance(raw, dict) and key in raw and isinstance(raw[key], dict):
        return raw[key]
    return raw


# --------------------------------------------------------------------------
# Actual assertions
# --------------------------------------------------------------------------

def test_l4_c01_upstream_resolver_returns_prepend_command(disposable_project: Path) -> None:
    _write_rdx_tea_overlay(disposable_project)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    merged = _run_resolver(disposable_project, skill)
    prepend = merged.get("activation_steps_prepend") or []
    assert any(
        "prepare.py" in step and "--workflow test-design" in step
        for step in prepend
    ), f"prepend step missing prepare.py invocation: {prepend}"


def test_l4_c02_upstream_resolver_returns_active_context_bundle_path(disposable_project: Path) -> None:
    _write_rdx_tea_overlay(disposable_project)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    merged = _run_resolver(disposable_project, skill)
    facts = merged.get("persistent_facts") or []
    assert any(
        "_bmad/rdx-tea/runtime/test-design/active-context.md" in f
        for f in facts
    ), f"active-context bundle path not merged into persistent_facts: {facts}"


def test_l4_c03_upstream_resolver_returns_on_complete_binder(disposable_project: Path) -> None:
    _write_rdx_tea_overlay(disposable_project)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    merged = _run_resolver(disposable_project, skill)
    on_complete = merged.get("on_complete", "")
    assert "binder.py" in on_complete, (
        f"on_complete did not include binder invocation: {on_complete!r}"
    )
    assert "--workflow test-design" in on_complete


def test_l4_c04_upstream_resolver_preserves_base_persistent_facts(disposable_project: Path) -> None:
    """The upstream base `file:{project-root}/**/project-context.md` glob
    is not clobbered by our overlay (append semantics)."""
    _write_rdx_tea_overlay(disposable_project)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    merged = _run_resolver(disposable_project, skill)
    facts = merged.get("persistent_facts") or []
    assert any("project-context.md" in f for f in facts), (
        f"base persistent_facts entry lost after RDX overlay merge: {facts}"
    )


def test_l4_c05_upstream_resolver_preserves_user_override(disposable_project: Path) -> None:
    """A `.user.toml` overlay appends AFTER the team overlay and MUST NOT
    be clobbered."""
    _write_rdx_tea_overlay(disposable_project, extra_user_overlay=True)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    merged = _run_resolver(disposable_project, skill)
    facts = merged.get("persistent_facts") or []
    assert any("Playwright" in f for f in facts), (
        f"user overlay lost: {facts}"
    )


def test_l4_c06_upstream_resolver_produces_valid_toml_shape(disposable_project: Path) -> None:
    """No duplicate `[workflow]` tables, no NULs, well-formed dict."""
    _write_rdx_tea_overlay(disposable_project)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    merged = _run_resolver(disposable_project, skill)
    assert isinstance(merged, dict)
    # A `[workflow]` block that got merged twice (the historic bug) would
    # produce keys nested wrong. Check we have flat expected keys.
    for k in ("activation_steps_prepend", "persistent_facts", "on_complete"):
        assert k in merged, f"missing top-level key {k}"


def test_l4_c07_no_skill_root_modifications(disposable_project: Path) -> None:
    """After a full resolve, the upstream skill directory must be
    byte-identical to the pristine copy."""
    _write_rdx_tea_overlay(disposable_project, extra_user_overlay=True)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    _ = _run_resolver(disposable_project, skill)
    # Compare each file byte-for-byte.
    import hashlib
    for pristine in UPSTREAM_TESTARCH_TESTDESIGN.rglob("*"):
        if not pristine.is_file():
            continue
        rel = pristine.relative_to(UPSTREAM_TESTARCH_TESTDESIGN)
        candidate = skill / rel
        assert candidate.exists(), f"skill lost {rel}"
        assert (
            hashlib.sha256(pristine.read_bytes()).hexdigest()
            == hashlib.sha256(candidate.read_bytes()).hexdigest()
        ), f"skill file mutated: {rel}"


def test_l4_c08_resolver_exit_code_is_zero(disposable_project: Path) -> None:
    """Sanity: the resolver must exit 0 for a well-formed overlay."""
    _write_rdx_tea_overlay(disposable_project)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    result = subprocess.run(
        [str(VENV_PY), str(RESOLVER),
         "--skill", str(skill), "--key", "workflow"],
        cwd=str(disposable_project),
        capture_output=True, text=True,
    )
    assert result.returncode == 0, f"stderr: {result.stderr}"


def test_l4_c09_resolver_output_is_reproducible(disposable_project: Path) -> None:
    """Two consecutive invocations produce identical JSON."""
    _write_rdx_tea_overlay(disposable_project)
    skill = disposable_project / ".claude" / "skills" / "bmad-testarch-test-design"
    a = _run_resolver(disposable_project, skill)
    b = _run_resolver(disposable_project, skill)
    assert a == b
