#!/usr/bin/env sh
# RDX pre-push hook — Phase 5.
#
# Sentinel: # RDX-HOOK-MANAGED
# Do not edit this file by hand. Re-run install-hook.py to refresh.
#
# This hook is a SOFT gate. It can be bypassed by `git push --no-verify`.
# The bypass is recorded in .git/hooks/.rdx-bypass.log so CI can flag
# it. Hard enforcement lives in the CI required check.

set -u

HOOK_DIR="$(dirname "$0")"
GIT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "${GIT_ROOT:-}" ]; then
    echo "[RDX hook] not inside a git repo, skipping" >&2
    exit 0
fi

# 1. Resolve which validator to run.
if [ -n "${RDX_VALIDATOR:-}" ]; then
    VALIDATOR_CMD="$RDX_VALIDATOR"
elif [ -d "$GIT_ROOT/rdx-validator/rdx_validator" ]; then
    VALIDATOR_CMD="python3 $GIT_ROOT/rdx-validator/rdx_validator/cli.py"
elif python3 -c "import rdx_validator" 2>/dev/null; then
    VALIDATOR_CMD="python3 -m rdx_validator"
else
    echo "[RDX hook] rdx-validator not available; declining to gate (set RDX_VALIDATOR or install package)" >&2
    # Fall through to user hook if present; do not block.
    if [ -x "$HOOK_DIR/pre-push.user.rdx-backup" ]; then
        exec "$HOOK_DIR/pre-push.user.rdx-backup" "$@"
    fi
    exit 0
fi

# 2. Read stdin (the standard pre-push hook contract).
#    Lines: <local ref> <local sha> <remote ref> <remote sha>
STDIN_PAYLOAD=$(cat)

FAIL=0
while IFS=' ' read -r LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA; do
    [ -z "$LOCAL_SHA" ] && continue
    # Skip deletions (local_sha == 0000000...).
    case "$LOCAL_SHA" in
        0000000000000000000000000000000000000000) continue ;;
    esac
    if [ "$REMOTE_SHA" = "0000000000000000000000000000000000000000" ]; then
        BASE_REF=$(git merge-base "$LOCAL_SHA" "$(git rev-parse HEAD~1 2>/dev/null || echo "$LOCAL_SHA")" 2>/dev/null || echo "$LOCAL_SHA")
    else
        BASE_REF="$REMOTE_SHA"
    fi

    # Locate STORY.json if present (optional; absence is fine).
    STORY_ARG=""
    if [ -f "$GIT_ROOT/STORY.json" ]; then
        STORY_ARG="--story $GIT_ROOT/STORY.json"
    fi

    # 3. Run the validator. Suppress its stdout JSON by routing it to a
    #    temp file so the hook output stays terse for developers.
    OUT=$(mktemp)
    # shellcheck disable=SC2086
    $VALIDATOR_CMD \
        --project-root "$GIT_ROOT" \
        $STORY_ARG \
        --base "$BASE_REF" \
        --head "$LOCAL_SHA" \
        --mode "${RDX_MODE:-MODE_2}" \
        --quiet \
        >"$OUT" 2>&1
    RC=$?
    if [ $RC -ne 0 ]; then
        echo "" >&2
        echo "[RDX] pre-push validator returned exit $RC for $LOCAL_REF" >&2
        echo "[RDX] re-run locally: $VALIDATOR_CMD --project-root $GIT_ROOT $STORY_ARG --base $BASE_REF --head $LOCAL_SHA --mode \${RDX_MODE:-MODE_2}" >&2
        echo "[RDX] bypass (auditable, recorded): git push --no-verify" >&2
        FAIL=1
    fi
    rm -f "$OUT"
done <<EOF
$STDIN_PAYLOAD
EOF

# 4. Run pre-existing user hook (chain) if present.
USER_HOOK="$HOOK_DIR/pre-push.user.rdx-backup"
if [ -x "$USER_HOOK" ]; then
    printf "%s" "$STDIN_PAYLOAD" | "$USER_HOOK" "$@"
    USER_RC=$?
    if [ $USER_RC -ne 0 ]; then
        FAIL=1
    fi
fi

if [ $FAIL -ne 0 ]; then
    exit 1
fi
exit 0
